build_settings:
  clone_depth: 1
  ignore:
    - vendor
    - tests

setup:
  composer:
    action: install

test:
  php_code_sniffer:
    standard: "PSR2"
    directory: "src"
    allowed_warnings: 0
    allowed_errors: 0

complete:
  email:
    default_mailto_address: poisoncorpsee@gmail.com
